### ISSUE TITLE
update prices continuously

### ISSUE THREAD

**Issue by iceberg1369** [SamadiPour/bonbast#5]
please add argument to update prices continuously on 1 second interval eg.

**Comment by SamadiPour** [comment]
I have some plans for live/continuous price, but I will work on it after figuring out what arguments I want to use and how I want to show it.
If you have any ideas or suggestions, feel free to share.

**Comment by MrOplus** [comment]
bonbast will block your IP address if you keep sending requests more than its rate limiter's limit, so I think it's not even possible.

**Comment by SamadiPour** [comment]
@kooroshh Yes and no.
Yes, It will ban you if you send requests every second. But the site has an update functionality that sends requests every 30 seconds.
Since we will act like a regular user, we can implement continuous price updates and set the default interval to 30 seconds.
If anyone wants to change the interval, they are free to do it, and they might get banned.
